[package]
name = "verve"
version = "0.1.0"
authors = ["Charles Gunn <cjgunnmail@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.2"
rustyline = "5.0.3"
colored = "1.8"